var searchData=
[
  ['characteristic_0',['Characteristic',['../namespacei_shop_main_ver2_1_1_config_1_1_characteristic.html',1,'iShopMainVer2.Config.Characteristic'],['../namespacei_shop_main_ver2_1_1_models_1_1_entity_1_1_characteristic.html',1,'iShopMainVer2.Models.Entity.Characteristic']]],
  ['config_1',['Config',['../namespacei_shop_main_ver2_1_1_config.html',1,'iShopMainVer2']]],
  ['controllers_2',['Controllers',['../namespacei_shop_main_ver2_1_1_controllers.html',1,'iShopMainVer2']]],
  ['data_3',['Data',['../namespacei_shop_main_ver2_1_1_data.html',1,'iShopMainVer2']]],
  ['dto_4',['Dto',['../namespacei_shop_main_ver2_1_1_models_1_1_dto.html',1,'iShopMainVer2::Models']]],
  ['entity_5',['Entity',['../namespacei_shop_main_ver2_1_1_models_1_1_entity.html',1,'iShopMainVer2::Models']]],
  ['helpers_6',['Helpers',['../namespacei_shop_main_ver2_1_1_helpers.html',1,'iShopMainVer2']]],
  ['id_7',['Id',['../classi_shop_main_ver2_1_1_models_1_1_dto_1_1_authorization_user_dto.html#a7d9f6b4f3d5f48ddf6f2e853e15fbb1d',1,'iShopMainVer2.Models.Dto.AuthorizationUserDto.Id'],['../interfacei_shop_main_ver2_1_1_models_1_1_dto_1_1_i_dto.html#a7b4aa39e879219a8d9d45e8c765d7db0',1,'iShopMainVer2.Models.Dto.IDto.Id'],['../classi_shop_main_ver2_1_1_models_1_1_dto_1_1_registration_user_dto.html#ac95ea2ed02e4bec6d6821df930dd31f2',1,'iShopMainVer2.Models.Dto.RegistrationUserDto.Id'],['../classi_shop_main_ver2_1_1_models_1_1_entity_1_1_base_entity.html#a6418d8fb850caeed94ba6d5363a87739',1,'iShopMainVer2.Models.Entity.BaseEntity.Id']]],
  ['idto_8',['IDto',['../interfacei_shop_main_ver2_1_1_models_1_1_dto_1_1_i_dto.html',1,'iShopMainVer2::Models::Dto']]],
  ['idto_2ecs_9',['IDto.cs',['../_i_dto_8cs.html',1,'']]],
  ['index_10',['Index',['../classi_shop_main_ver2_1_1_models_1_1_entity_1_1_order_1_1_address_entity.html#abde2bd8f2f8868f93cbcc0117faefb82',1,'iShopMainVer2::Models::Entity::Order::AddressEntity']]],
  ['information_11',['Information',['../classi_shop_main_ver2_1_1_models_1_1_entity_1_1_user_info_1_1_user_entity.html#aef2866f0fb8655ce30fb4459aea6271c',1,'iShopMainVer2::Models::Entity::UserInfo::UserEntity']]],
  ['informationconfiguration_12',['InformationConfiguration',['../classi_shop_main_ver2_1_1_config_1_1_user_1_1_information_configuration.html',1,'iShopMainVer2::Config::User']]],
  ['informationconfiguration_2ecs_13',['InformationConfiguration.cs',['../_information_configuration_8cs.html',1,'']]],
  ['informationentity_14',['InformationEntity',['../classi_shop_main_ver2_1_1_models_1_1_entity_1_1_user_info_1_1_information_entity.html',1,'iShopMainVer2::Models::Entity::UserInfo']]],
  ['informationentity_2ecs_15',['InformationEntity.cs',['../_information_entity_8cs.html',1,'']]],
  ['informationid_16',['InformationId',['../classi_shop_main_ver2_1_1_models_1_1_entity_1_1_user_info_1_1_user_entity.html#a4cc46752e21f14c063a5cb55913b8882',1,'iShopMainVer2::Models::Entity::UserInfo::UserEntity']]],
  ['informationrepository_17',['InformationRepository',['../classi_shop_main_ver2_1_1_repositories_1_1_user_1_1_information_repository.html#af11701ec3c58e010a2d3287df610999d',1,'iShopMainVer2.Repositories.User.InformationRepository.InformationRepository()'],['../classi_shop_main_ver2_1_1_repositories_1_1_user_1_1_information_repository.html',1,'iShopMainVer2.Repositories.User.InformationRepository']]],
  ['informationrepository_2ecs_18',['InformationRepository.cs',['../_information_repository_8cs.html',1,'']]],
  ['informations_19',['Informations',['../classi_shop_main_ver2_1_1_data_1_1_application_db_context.html#a6873e781e9751e7645e4e009bf4b4e1e',1,'iShopMainVer2::Data::ApplicationDbContext']]],
  ['init_20',['init',['../classi_shop_main_ver2_1_1_migrations_1_1init.html',1,'iShopMainVer2::Migrations']]],
  ['initializeasync_21',['InitializeAsync',['../interfacei_shop_main_ver2_1_1_services_1_1_i_service.html#a343abd20bcc8b9b37f931e4cae714cf5',1,'iShopMainVer2.Services.IService.InitializeAsync()'],['../classi_shop_main_ver2_1_1_services_1_1_user_service.html#a60649f57852aff023c0c3e1f6020f29a',1,'iShopMainVer2.Services.UserService.InitializeAsync()']]],
  ['iorderrepository_22',['IOrderRepository',['../interfacei_shop_main_ver2_1_1_repositories_1_1_order_1_1_i_order_repository.html',1,'iShopMainVer2::Repositories::Order']]],
  ['iorderrepository_2ecs_23',['IOrderRepository.cs',['../_i_order_repository_8cs.html',1,'']]],
  ['iorderrepository_3c_20addressentity_20_3e_24',['IOrderRepository&lt; AddressEntity &gt;',['../interfacei_shop_main_ver2_1_1_repositories_1_1_order_1_1_i_order_repository.html',1,'iShopMainVer2::Repositories::Order']]],
  ['iorderservice_25',['IOrderService',['../classi_shop_main_ver2_1_1_services_1_1_i_order_service.html',1,'iShopMainVer2::Services']]],
  ['iorderservice_2ecs_26',['IOrderService.cs',['../_i_order_service_8cs.html',1,'']]],
  ['irepository_27',['IRepository',['../interfacei_shop_main_ver2_1_1_repositories_1_1_user_1_1_i_repository.html',1,'iShopMainVer2::Repositories::User']]],
  ['irepository_2ecs_28',['IRepository.cs',['../_i_repository_8cs.html',1,'']]],
  ['irepository_3c_20accountentity_20_3e_29',['IRepository&lt; AccountEntity &gt;',['../interfacei_shop_main_ver2_1_1_repositories_1_1_user_1_1_i_repository.html',1,'iShopMainVer2::Repositories::User']]],
  ['irepository_3c_20informationentity_20_3e_30',['IRepository&lt; InformationEntity &gt;',['../interfacei_shop_main_ver2_1_1_repositories_1_1_user_1_1_i_repository.html',1,'iShopMainVer2::Repositories::User']]],
  ['irepository_3c_20userentity_20_3e_31',['IRepository&lt; UserEntity &gt;',['../interfacei_shop_main_ver2_1_1_repositories_1_1_user_1_1_i_repository.html',1,'iShopMainVer2::Repositories::User']]],
  ['isauthorizationasync_32',['isAuthorizationAsync',['../interfacei_shop_main_ver2_1_1_services_1_1_i_service.html#ac764831a900b1e51cb74c32fe3e5e1c8',1,'iShopMainVer2.Services.IService.isAuthorizationAsync()'],['../classi_shop_main_ver2_1_1_services_1_1_user_service.html#a12ae05d05ccef86f5807c01075c0fb11',1,'iShopMainVer2.Services.UserService.isAuthorizationAsync()']]],
  ['iservice_33',['IService',['../interfacei_shop_main_ver2_1_1_services_1_1_i_service.html',1,'iShopMainVer2::Services']]],
  ['iservice_2ecs_34',['IService.cs',['../_i_service_8cs.html',1,'']]],
  ['isfastcharging_35',['IsFastCharging',['../classi_shop_main_ver2_1_1_models_1_1_entity_1_1_characteristic_1_1_power_entity.html#a44a44d332f4aa76c0ea132f71e8f2768',1,'iShopMainVer2::Models::Entity::Characteristic::PowerEntity']]],
  ['ishopmainver2_36',['iShopMainVer2',['../namespacei_shop_main_ver2.html',1,'']]],
  ['ishopmainver2_2eassemblyinfo_2ecs_37',['iShopMainVer2.AssemblyInfo.cs',['../net6_80_2i_shop_main_ver2_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../net7_80_2i_shop_main_ver2_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['ishopmainver2_2eglobalusings_2eg_2ecs_38',['iShopMainVer2.GlobalUsings.g.cs',['../net6_80_2i_shop_main_ver2_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../net7_80_2i_shop_main_ver2_8_global_usings_8g_8cs.html',1,'(Global Namespace)']]],
  ['ispowerunit_39',['IsPowerUnit',['../classi_shop_main_ver2_1_1_models_1_1_entity_1_1_characteristic_1_1_power_entity.html#a13fb63409a361fc02f77b7642e4e3329',1,'iShopMainVer2::Models::Entity::Characteristic::PowerEntity']]],
  ['istouchscreen_40',['IsTouchScreen',['../classi_shop_main_ver2_1_1_models_1_1_entity_1_1_characteristic_1_1_screen_entity.html#a662b8a2c25a71f3ec76edba6bfc7fb1d',1,'iShopMainVer2::Models::Entity::Characteristic::ScreenEntity']]],
  ['iswirelesscharging_41',['IsWirelessCharging',['../classi_shop_main_ver2_1_1_models_1_1_entity_1_1_characteristic_1_1_power_entity.html#ac571311ac1610cf64b8ce9fa94aca3ae',1,'iShopMainVer2::Models::Entity::Characteristic::PowerEntity']]],
  ['migrations_42',['Migrations',['../namespacei_shop_main_ver2_1_1_migrations.html',1,'iShopMainVer2']]],
  ['models_43',['Models',['../namespacei_shop_main_ver2_1_1_models.html',1,'iShopMainVer2']]],
  ['order_44',['Order',['../namespacei_shop_main_ver2_1_1_config_1_1_order.html',1,'iShopMainVer2.Config.Order'],['../namespacei_shop_main_ver2_1_1_models_1_1_entity_1_1_order.html',1,'iShopMainVer2.Models.Entity.Order'],['../namespacei_shop_main_ver2_1_1_repositories_1_1_order.html',1,'iShopMainVer2.Repositories.Order']]],
  ['orderdto_45',['OrderDto',['../namespacei_shop_main_ver2_1_1_models_1_1_dto_1_1_order_dto.html',1,'iShopMainVer2::Models::Dto']]],
  ['product_46',['Product',['../namespacei_shop_main_ver2_1_1_config_1_1_product.html',1,'iShopMainVer2::Config']]],
  ['products_47',['Products',['../namespacei_shop_main_ver2_1_1_config_1_1_products.html',1,'iShopMainVer2.Config.Products'],['../namespacei_shop_main_ver2_1_1_models_1_1_entity_1_1_products.html',1,'iShopMainVer2.Models.Entity.Products']]],
  ['repositories_48',['Repositories',['../namespacei_shop_main_ver2_1_1_repositories.html',1,'iShopMainVer2']]],
  ['requestdto_49',['RequestDto',['../namespacei_shop_main_ver2_1_1_models_1_1_dto_1_1_request_dto.html',1,'iShopMainVer2::Models::Dto']]],
  ['services_50',['Services',['../namespacei_shop_main_ver2_1_1_services.html',1,'iShopMainVer2']]],
  ['user_51',['User',['../namespacei_shop_main_ver2_1_1_config_1_1_user.html',1,'iShopMainVer2.Config.User'],['../namespacei_shop_main_ver2_1_1_repositories_1_1_user.html',1,'iShopMainVer2.Repositories.User']]],
  ['userinfo_52',['UserInfo',['../namespacei_shop_main_ver2_1_1_models_1_1_entity_1_1_user_info.html',1,'iShopMainVer2::Models::Entity']]]
];
